language: java
jdk:
  - openjdk8
script:
  - ./gradlew build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build/deploy-me
  on:
    branch: master
